// AI Label Checker — image provenance / metadata parser.
//
// Reads the metadata that social platforms actually use to decide whether to
// stamp an "AI info" badge on a post:
//
//   1. IPTC DigitalSourceType   (in the XMP packet)  — what Instagram reads
//   2. C2PA Content Credentials (JUMBF / caBX box)   — what LinkedIn + TikTok read
//   3. EXIF Software / XMP CreatorTool               — which tool wrote the file
//   4. EXIF Make / Model                             — evidence of a real camera
//
// Dependency-free byte walking. No sharp, no exiftool, no c2patool.
//
// TWO LIMITATIONS, and the UI must state both:
//   - We detect the PRESENCE and readable claims of a C2PA manifest. We do NOT
//     verify its cryptographic signature.
//   - No metadata check can predict a platform's own image classifier, which
//     runs on top of all of this.
//
// NOTE: the PLATFORM_READS matrix below is mirrored in the portal's PHP copy at
// `AW PORTAL/includes/ai-label.php` (ail_platforms). Platforms change what they
// read. When you update one, update the other.

import { inflateSync } from "zlib";

export const AIL_MAX_BYTES = 25 * 1024 * 1024;

/**
 * label    — the platform reads a tag this file carries, and that tag declares AI.
 * possible — the file declares AI, but via a tag THIS platform does not read.
 *            Metadata will not trigger it, but the platform's own classifier might.
 * clear    — nothing in the file declares AI at all.
 */
export type Verdict = "label" | "possible" | "clear";

export interface SourceTypeMeaning {
  ai: boolean;
  plain: string;
  detail: string;
}

/**
 * IPTC DigitalSourceType vocabulary.
 * http://cv.iptc.org/newscodes/digitalsourcetype
 * `ai` = does this value tell a platform "there is AI in here".
 */
export const SOURCE_TYPES: Record<string, SourceTypeMeaning> = {
  trainedAlgorithmicMedia: {
    ai: true,
    plain: "Created entirely by an AI model",
    detail:
      "The file declares it was fully generated by a trained AI model.",
  },
  compositeWithTrainedAlgorithmicMedia: {
    ai: true,
    plain: "Real content with AI elements added",
    detail:
      "The file declares AI was used on part of it. This is the tag that generative fill, AI remove and AI expand write onto otherwise real photos.",
  },
  algorithmicMedia: {
    ai: true,
    plain: "Created by an algorithm",
    detail:
      "Made by software rather than a camera, but not by a trained AI model. Platforms are inconsistent about this one.",
  },
  algorithmicallyEnhanced: {
    ai: false,
    plain: "Real content, algorithmically enhanced",
    detail:
      "Enhanced by software but not generated. Not normally treated as AI content.",
  },
  composite: {
    ai: false,
    plain: "A composite of real content",
    detail: "Multiple real sources combined. Not an AI declaration.",
  },
  compositeCapture: {
    ai: false,
    plain: "A composite of real captures",
    detail:
      "Multiple camera captures combined, for example a panorama. Not an AI declaration.",
  },
  digitalCapture: {
    ai: false,
    plain: "Shot on a real camera",
    detail: "The file declares it came off a camera sensor.",
  },
  minorHumanEdits: {
    ai: false,
    plain: "Real content, lightly edited",
    detail: "Not an AI declaration.",
  },
  softwareImage: {
    ai: false,
    plain: "Made in software",
    detail: "A screenshot, chart or design file. Not an AI declaration.",
  },
};

/** Tool fingerprints. `ai` marks tools whose presence implies generative work. */
const TOOL_SIGNATURES: { name: string; needle: string; ai: boolean }[] = [
  { name: "Adobe Firefly", needle: "firefly", ai: true },
  { name: "OpenAI DALL-E", needle: "dall-e", ai: true },
  { name: "OpenAI DALL-E", needle: "dalle", ai: true },
  { name: "OpenAI GPT Image", needle: "gpt-image", ai: true },
  { name: "OpenAI Sora", needle: "sora", ai: true },
  { name: "Midjourney", needle: "midjourney", ai: true },
  { name: "Stable Diffusion", needle: "stable diffusion", ai: true },
  { name: "Google Imagen", needle: "imagen", ai: true },
  { name: "Google Gemini", needle: "gemini", ai: true },
  { name: "Grok / xAI", needle: "grok", ai: true },
  { name: "Flux", needle: "flux", ai: true },
  { name: "Ideogram", needle: "ideogram", ai: true },
  { name: "Leonardo", needle: "leonardo", ai: true },
  { name: "Runway", needle: "runway", ai: true },
  { name: "Adobe Photoshop", needle: "photoshop", ai: false },
  { name: "Adobe Lightroom", needle: "lightroom", ai: false },
  { name: "Adobe Express", needle: "adobe express", ai: false },
  { name: "Canva", needle: "canva", ai: false },
  { name: "Figma", needle: "figma", ai: false },
  { name: "Affinity", needle: "affinity", ai: false },
];

/**
 * Which metadata each platform actually reads.
 * Source: IPTC's cross-platform testing plus the platforms' own announcements.
 * This WILL drift. Revisit it, and keep the PHP copy in step.
 */
export const PLATFORM_READS: {
  key: string;
  label: string;
  reads: ("iptc" | "c2pa")[];
}[] = [
  { key: "meta", label: "Instagram / Facebook", reads: ["iptc"] },
  { key: "linkedin", label: "LinkedIn", reads: ["c2pa"] },
  { key: "tiktok", label: "TikTok", reads: ["c2pa"] },
  { key: "youtube", label: "YouTube", reads: ["c2pa"] },
  { key: "pinterest", label: "Pinterest", reads: ["iptc", "c2pa"] },
];

// ---------------------------------------------------------------------------
// Container walkers. All of this parses hostile input, so bounds-check hard.
// ---------------------------------------------------------------------------

interface Bag {
  xmp: string[];
  exif: Buffer[];
  c2pa: string[];
  text: string[];
}

const newBag = (): Bag => ({ xmp: [], exif: [], c2pa: [], text: [] });

function walkJpeg(b: Buffer, bag: Bag): Bag {
  const len = b.length;
  let i = 2; // skip FFD8

  while (i + 4 <= len) {
    if (b[i] !== 0xff) {
      i++;
      continue;
    }
    const marker = b[i + 1];
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      i += 2;
      continue;
    }
    if (marker === 0xda || marker === 0xd9) break; // start of scan / end of image

    const seglen = b.readUInt16BE(i + 2);
    if (seglen < 2 || i + 2 + seglen > len) break;
    const data = b.subarray(i + 4, i + 2 + seglen);

    if (marker === 0xe1) {
      const head = data.subarray(0, 80).toString("latin1");
      if (head.startsWith("Exif\0\0")) {
        bag.exif.push(data.subarray(6));
      } else if (head.includes("ns.adobe.com/xap/1.0/")) {
        const nul = data.indexOf(0);
        bag.xmp.push(data.subarray(nul === -1 ? 0 : nul + 1).toString("utf8"));
      } else if (head.includes("ns.adobe.com/xmp/extension/")) {
        bag.xmp.push(data.toString("utf8"));
      }
    } else if (marker === 0xeb) {
      bag.c2pa.push(data.toString("latin1")); // APP11 JUMBF, carries C2PA
    } else if (marker === 0xed) {
      bag.text.push(data.toString("latin1")); // APP13 Photoshop IRB / legacy IPTC
    }

    i += 2 + seglen;
  }
  return bag;
}

function walkPng(b: Buffer, bag: Bag): Bag {
  const len = b.length;
  let i = 8; // skip signature

  while (i + 8 <= len) {
    const clen = b.readUInt32BE(i);
    const type = b.subarray(i + 4, i + 8).toString("latin1");
    if (clen < 0 || i + 12 + clen > len) break;
    const data = b.subarray(i + 8, i + 8 + clen);

    if (type === "iTXt") {
      // keyword \0 compFlag compMethod lang \0 translated \0 text
      const p = data.indexOf(0);
      if (p !== -1) {
        const keyword = data.subarray(0, p).toString("latin1");
        const compFlag = data[p + 1] ?? 0;
        const rest = data.subarray(p + 3);
        const q = rest.indexOf(0);
        const r = q === -1 ? -1 : rest.indexOf(0, q + 1);
        let text = r === -1 ? Buffer.alloc(0) : rest.subarray(r + 1);
        if (compFlag === 1 && text.length) {
          try {
            text = inflateSync(text);
          } catch {
            text = Buffer.alloc(0);
          }
        }
        if (text.length) {
          const s = text.toString("utf8");
          if (/xmp/i.test(keyword)) bag.xmp.push(s);
          else bag.text.push(`${keyword}: ${s}`);
        }
      }
    } else if (type === "tEXt") {
      const p = data.indexOf(0);
      if (p !== -1) {
        bag.text.push(
          `${data.subarray(0, p).toString("latin1")}: ${data.subarray(p + 1).toString("latin1")}`,
        );
      }
    } else if (type === "zTXt") {
      const p = data.indexOf(0);
      if (p !== -1) {
        try {
          bag.text.push(
            `${data.subarray(0, p).toString("latin1")}: ${inflateSync(data.subarray(p + 2)).toString("utf8")}`,
          );
        } catch {
          /* corrupt chunk, skip */
        }
      }
    } else if (type === "eXIf") {
      bag.exif.push(Buffer.from(data));
    } else if (type === "caBX") {
      bag.c2pa.push(data.toString("latin1")); // C2PA in PNG
    }

    if (type === "IEND") break;
    i += 12 + clen;
  }
  return bag;
}

function walkWebp(b: Buffer, bag: Bag): Bag {
  const len = b.length;
  let i = 12; // RIFF____WEBP

  while (i + 8 <= len) {
    const fourcc = b.subarray(i, i + 4).toString("latin1");
    const clen = b.readUInt32LE(i + 4);
    if (clen < 0 || i + 8 + clen > len) break;
    const data = b.subarray(i + 8, i + 8 + clen);

    if (fourcc === "XMP ") bag.xmp.push(data.toString("utf8"));
    else if (fourcc === "EXIF") {
      bag.exif.push(
        Buffer.from(
          data.subarray(0, 6).toString("latin1") === "Exif\0\0" ? data.subarray(6) : data,
        ),
      );
    } else if (fourcc === "C2PA") bag.c2pa.push(data.toString("latin1"));

    i += 8 + clen + (clen % 2); // chunks are even-padded
  }
  return bag;
}

// ---------------------------------------------------------------------------
// EXIF: minimal TIFF IFD walker. We only want Make, Model and Software.
// ---------------------------------------------------------------------------

function readExif(t: Buffer): Record<string, string> {
  const out: Record<string, string> = {};
  if (t.length < 8) return out;

  const bo = t.subarray(0, 2).toString("latin1");
  if (bo !== "II" && bo !== "MM") return out;
  const le = bo === "II";

  const u16 = (o: number) =>
    t.length >= o + 2 ? (le ? t.readUInt16LE(o) : t.readUInt16BE(o)) : 0;
  const u32 = (o: number) =>
    t.length >= o + 4 ? (le ? t.readUInt32LE(o) : t.readUInt32BE(o)) : 0;

  if (u16(2) !== 42) return out;
  const ifd = u32(4);
  if (ifd < 8 || ifd + 2 > t.length) return out;

  const count = u16(ifd);
  if (count > 512) return out; // sanity guard on malformed input

  const wanted: Record<number, string> = {
    0x010f: "make",
    0x0110: "model",
    0x0131: "software",
  };

  for (let n = 0; n < count; n++) {
    const e = ifd + 2 + n * 12;
    if (e + 12 > t.length) break;

    const tag = u16(e);
    if (!wanted[tag]) continue;
    if (u16(e + 2) !== 2) continue; // ASCII only

    const cnt = u32(e + 4);
    if (cnt < 1 || cnt > 4096) continue;

    const start = cnt <= 4 ? e + 8 : u32(e + 8);
    if (start + cnt > t.length) continue;

    const val = t
      .subarray(start, start + cnt)
      .toString("latin1")
      .replace(/\0/g, "")
      .trim();
    if (val) out[wanted[tag]] = val;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Signal extraction
// ---------------------------------------------------------------------------

function findSourceType(s: string): string | null {
  let m = s.match(/digitalsourcetype\/([A-Za-z]+)/i);
  if (m) return m[1];
  m = s.match(/DigitalSourceType["'>\s]+([A-Za-z]+)/i);
  return m ? m[1] : null;
}

function findXmpTag(s: string, tag: string): string | null {
  let m = s.match(new RegExp(`<[A-Za-z0-9]+:${tag}>([^<]{1,200})</`, "i"));
  if (m) return m[1].trim();
  m = s.match(new RegExp(`[A-Za-z0-9]+:${tag}="([^"]{1,200})"`, "i"));
  return m ? m[1].trim() : null;
}

interface C2paInfo {
  present: boolean;
  generator: string | null;
  sourceType: string | null;
  actions: string[];
}

/**
 * Read a CBOR text string at `pos`. Major type 3: 0x60|len for len < 24,
 * 0x78 + 1 length byte, 0x79 + 2 length bytes. Enough for the short label
 * strings we want; anything else we treat as absent.
 */
function cborTextAt(buf: string, pos: number): string | null {
  const b = buf.charCodeAt(pos);
  let len: number;
  let start: number;

  if (b >= 0x60 && b <= 0x77) {
    len = b - 0x60;
    start = pos + 1;
  } else if (b === 0x78) {
    len = buf.charCodeAt(pos + 1);
    start = pos + 2;
  } else if (b === 0x79) {
    len = (buf.charCodeAt(pos + 1) << 8) | buf.charCodeAt(pos + 2);
    start = pos + 3;
  } else {
    return null;
  }

  if (!Number.isFinite(len) || len < 1 || len > 200) return null;
  const s = buf.slice(start, start + len);
  // Reject anything non-printable: we mis-read the offset if that happens.
  return /^[\x20-\x7E]+$/.test(s) ? s : null;
}

/** Find a CBOR map key by name, then read the text value that follows it. */
function cborTextAfterKey(buf: string, key: string, from = 0): string | null {
  const i = buf.indexOf(key, from);
  return i === -1 ? null : cborTextAt(buf, i + key.length);
}

/**
 * Pull a human-readable generator name out of the manifest.
 *
 * C2PA v2 uses `claim_generator_info`, a map of name + version. Note that a
 * naive search for `claim_generator` prefix-matches that key and reads back
 * "info", so the v2 form has to be tried FIRST.
 */
function extractGenerator(joined: string): string | null {
  // Collect both: claim_generator_info names the product ("OpenAI Media
  // Service API") while softwareAgent names the actual model ("gpt-image 2.0").
  // The model is the useful half for spotting which tool did it.
  const parts: string[] = [];
  for (const anchor of ["claim_generator_info", "softwareAgent"]) {
    const i = joined.indexOf(anchor);
    if (i === -1) continue;
    const name = cborTextAfterKey(joined, "name", i);
    if (!name) continue;
    const version = cborTextAfterKey(joined, "version", i);
    const s = version ? `${name} ${version}` : name;
    if (!parts.includes(s)) parts.push(s);
  }
  if (parts.length) return parts.join(" / ");

  // C2PA v1: claim_generator is a plain string.
  const v1 = cborTextAfterKey(joined, "claim_generator");
  return v1 && !v1.startsWith("info") ? v1 : null;
}

/**
 * C2PA manifests are CBOR inside JUMBF. We do not decode the whole structure —
 * the strings we want sit in the payload as readable UTF-8, so a targeted read
 * gets them.
 */
function readC2pa(blobs: string[]): C2paInfo {
  const joined = blobs.join("\n");
  const out: C2paInfo = {
    present: false,
    generator: null,
    sourceType: null,
    actions: [],
  };
  if (!joined) return out;

  out.present = joined.includes("c2pa") || joined.includes("jumd");
  if (!out.present) return out;

  out.generator = extractGenerator(joined);
  out.sourceType = findSourceType(joined);

  for (const a of [
    "c2pa.created",
    "c2pa.edited",
    "c2pa.placed",
    "c2pa.opened",
    "c2pa.converted",
    "c2pa.published",
  ]) {
    if (joined.includes(a)) out.actions.push(a);
  }
  return out;
}

function matchTools(haystack: string): { name: string; ai: boolean }[] {
  const h = haystack.toLowerCase();
  return TOOL_SIGNATURES.filter((s) => h.includes(s.needle)).map((s) => ({
    name: s.name,
    ai: s.ai,
  }));
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export interface PlatformVerdict {
  key: string;
  platform: string;
  verdict: Verdict;
  because: string;
}

export interface AiLabelSignals {
  iptcSourceType: string | null;
  iptcMeaning: SourceTypeMeaning | null;
  iptcIsAi: boolean;
  c2paPresent: boolean;
  c2paGenerator: string | null;
  c2paSourceType: string | null;
  c2paActions: string[];
  c2paIsAi: boolean;
  creatorTool: string | null;
  camera: string | null;
  toolsDetected: string[];
  hasAnyMetadata: boolean;
}

export interface AiLabelResult {
  ok: true;
  filename: string;
  format: string;
  sizeKb: number;
  signals: AiLabelSignals;
  verdicts: PlatformVerdict[];
  flaggedBy: number;
  summary: string;
  /** Set when the file carries no metadata at all, so the check is inconclusive. */
  stripped: boolean;
}

export interface AiLabelError {
  ok: false;
  filename: string;
  error: string;
}

export function analyseImage(
  bytes: Buffer,
  filename = "",
): AiLabelResult | AiLabelError {
  if (!bytes.length) return { ok: false, filename, error: "Empty file." };
  if (bytes.length > AIL_MAX_BYTES)
    return { ok: false, filename, error: "File is too large to check (25MB limit)." };

  let bag = newBag();
  let format: string;

  const sig = bytes.subarray(0, 8);
  if (sig[0] === 0xff && sig[1] === 0xd8) {
    format = "JPEG";
    bag = walkJpeg(bytes, bag);
  } else if (sig.subarray(0, 8).toString("latin1") === "\x89PNG\r\n\x1a\n") {
    format = "PNG";
    bag = walkPng(bytes, bag);
  } else if (
    sig.subarray(0, 4).toString("latin1") === "RIFF" &&
    bytes.subarray(8, 12).toString("latin1") === "WEBP"
  ) {
    format = "WebP";
    bag = walkWebp(bytes, bag);
  } else {
    return {
      ok: false,
      filename,
      error: "Unsupported file type. Use JPG, PNG or WebP.",
    };
  }

  const xmp = bag.xmp.join("\n");
  const texts = bag.text.join("\n");
  const c2pa = readC2pa(bag.c2pa);

  let exif: Record<string, string> = {};
  for (const blob of bag.exif) exif = { ...exif, ...readExif(blob) };

  const iptcType = findSourceType(xmp) ?? findSourceType(texts);
  const creator = findXmpTag(xmp, "CreatorTool") ?? exif.software ?? null;

  const iptcMeaning = iptcType ? (SOURCE_TYPES[iptcType] ?? null) : null;
  const iptcAi = !!iptcMeaning?.ai;

  const c2paTypeAi = c2pa.sourceType
    ? !!SOURCE_TYPES[c2pa.sourceType]?.ai
    : false;
  const genTools = c2pa.generator ? matchTools(c2pa.generator) : [];
  const c2paAi = c2paTypeAi || genTools.some((t) => t.ai);

  const allTools = matchTools(
    [c2pa.generator, creator, texts].filter(Boolean).join(" "),
  );
  const camera = [exif.make, exif.model].filter(Boolean).join(" ").trim() || null;

  // Does the file declare AI at all, by any route?
  const declaresAi = iptcAi || (c2pa.present && c2paAi);

  const verdicts: PlatformVerdict[] = PLATFORM_READS.map((p) => {
    const triggers: string[] = [];
    if (p.reads.includes("iptc") && iptcAi) triggers.push("iptc");
    if (p.reads.includes("c2pa") && c2pa.present && c2paAi) triggers.push("c2pa");

    // A platform that does not read the tag this file happens to carry will not
    // auto-label it, but the file IS still AI, so its classifier may catch it.
    // Calling that "clear" would be misleading.
    const verdict: Verdict = triggers.length
      ? "label"
      : declaresAi
        ? "possible"
        : "clear";

    return {
      key: p.key,
      platform: p.label,
      verdict,
      because: reasonFor(triggers, verdict, c2pa),
    };
  });

  const flaggedBy = verdicts.filter((v) => v.verdict === "label").length;
  const hasAnyMetadata =
    !!xmp || !!texts || Object.keys(exif).length > 0 || c2pa.present;

  return {
    ok: true,
    filename,
    format,
    sizeKb: Math.round(bytes.length / 1024),
    signals: {
      iptcSourceType: iptcType,
      iptcMeaning,
      iptcIsAi: iptcAi,
      c2paPresent: c2pa.present,
      c2paGenerator: c2pa.generator,
      c2paSourceType: c2pa.sourceType,
      c2paActions: c2pa.actions,
      c2paIsAi: c2paAi,
      creatorTool: creator,
      camera,
      toolsDetected: allTools.map((t) => t.name),
      hasAnyMetadata,
    },
    verdicts,
    flaggedBy,
    summary: summarise(iptcType, iptcAi, c2pa, camera, allTools, flaggedBy, hasAnyMetadata),
    stripped: !hasAnyMetadata,
  };
}

function reasonFor(
  triggers: string[],
  verdict: Verdict,
  c2pa: C2paInfo,
): string {
  // Keep these SHORT. They repeat once per platform, so anything wordy turns
  // the results card into a wall of near-identical paragraphs on mobile. The
  // detail (which tool, which tag) belongs in the summary and the detail panel,
  // where it is said once.
  if (triggers.includes("iptc")) {
    return `Reads the IPTC tag, and this file carries it.`;
  }
  if (triggers.includes("c2pa")) {
    return "Reads Content Credentials, and this file has them.";
  }
  if (verdict === "possible") {
    const carried = c2pa.present ? "Content Credentials" : "the IPTC tag";
    return `Does not read ${carried}, so it will not auto-label. Its own detection still might.`;
  }
  return "Nothing here to flag.";
}

function summarise(
  iptc: string | null,
  iptcAi: boolean,
  c2pa: C2paInfo,
  camera: string | null,
  tools: { name: string; ai: boolean }[],
  flagged: number,
  hasAnyMetadata: boolean,
): string {
  if (!hasAnyMetadata) {
    return "This file has no metadata at all, so there is nothing to check. That usually means it is a screenshot, or it was downloaded back off a platform, or re-saved by a tool that strips tags. Check the original export instead.";
  }

  if (flagged === 0 && !iptcAi && !c2pa.present) {
    if (camera)
      return `Clean. This file carries camera data from a ${camera} and nothing that declares AI. No platform should label it on metadata.`;
    return "Clean. Nothing in this file declares AI involvement, so no platform should label it on metadata alone.";
  }

  if (iptc === "compositeWithTrainedAlgorithmicMedia") {
    const shot = camera
      ? ` It also carries camera data from a ${camera}, so the underlying photo is real.`
      : "";
    return `This is the common false positive. The file is tagged as real content with AI elements added, which is what an AI remove, generative fill or AI expand writes even when the photo itself is genuine.${shot}`;
  }

  if (flagged === 0) {
    return "This file carries provenance data, but nothing in it declares AI. No platform should label it on metadata.";
  }

  const aiTools = tools.filter((t) => t.ai).map((t) => t.name);
  const who = aiTools.length
    ? aiTools.join(" and ")
    : (c2pa.generator ?? "an AI tool");
  return `This file declares AI involvement (${who}), so ${flagged} of the platforms checked will label it.`;
}
