import type { NextConfig } from "next";
import { readFileSync } from "fs";
import { join } from "path";

// 301 redirect map (old WordPress URLs → new pages). Generated by
// scripts/gen-redirects.mjs. Runs as a Node app on the 20i Cloud Server.
type Redirect = { source: string; destination: string; statusCode: number };
const redirectMap: Redirect[] = JSON.parse(
  readFileSync(join(process.cwd(), "redirects.json"), "utf8")
);

const nextConfig: NextConfig = {
  // Serve the most modern image format the browser supports.
  // AVIF is ~30-50% smaller than WebP, WebP ~25% smaller than JPEG.
  images: {
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 30, // 30 days
    // Add common widths used in next/image sizes attribute
    deviceSizes: [360, 414, 640, 750, 828, 1080, 1200, 1440, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },

  // Tree-shake heavy ESM packages on import (motion ships a lot of features)
  experimental: {
    optimizePackageImports: ["motion", "motion/react"],
  },

  // Modern browsers; smaller polyfill payload
  compress: true,
  poweredByHeader: false,

  // 301s from the old WordPress site so no SEO/link equity is lost at launch.
  async redirects() {
    return redirectMap;
  },

  // Long-cache static assets, short-cache HTML
  async headers() {
    return [
      {
        source: "/images/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/_next/static/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      // Security headers on every response. (No strict CSP — it would break
      // GTM / Meta Pixel / Clarity / Calendly / Trustpilot. X-Frame-Options
      // still blocks clickjacking.)
      {
        source: "/:path*",
        headers: [
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
          { key: "X-DNS-Prefetch-Control", value: "on" },
        ],
      },
    ];
  },
};

export default nextConfig;
